-- =====================================================================
-- SUPABASE COMPLETE DATABASE SCHEMA FOR TAP ACCOUNTING SOFTWARE
-- Run this script in your Supabase SQL Editor: 
-- Dashboard -> SQL Editor -> New Query -> Paste & Run
-- =====================================================================

-- 1. Create Tenants Table
CREATE TABLE IF NOT EXISTS public.tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Default Tenant',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert Default Tenant (ID: 1) if not existing
INSERT INTO public.tenants (id, name)
VALUES (1, 'Default Tenant')
ON CONFLICT (id) DO NOTHING;

-- 2. Create Companies Table (Stores Company Info & Master Settings)
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    financial_year TEXT NOT NULL,
    books_from TEXT NOT NULL,
    state TEXT,
    gstin TEXT,
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create Ledgers Table (Chart of Accounts Master)
CREATE TABLE IF NOT EXISTS public.ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    group_name TEXT NOT NULL,
    opening NUMERIC NOT NULL DEFAULT 0,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create Parties Table (Sundry Debtors & Creditors Master)
CREATE TABLE IF NOT EXISTS public.parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    group_name TEXT NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    gstin TEXT NOT NULL DEFAULT '',
    state TEXT,
    opening TEXT NOT NULL DEFAULT '0',
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Create Stock Items Table (Inventory Items Master)
CREATE TABLE IF NOT EXISTS public.stock_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    alias TEXT,
    group_name TEXT NOT NULL,
    unit TEXT NOT NULL,
    opening_qty NUMERIC NOT NULL DEFAULT 0,
    opening_rate NUMERIC NOT NULL DEFAULT 0,
    opening_value NUMERIC NOT NULL DEFAULT 0,
    valuation_method TEXT DEFAULT 'FIFO',
    gst_applicability TEXT,
    hsn_details TEXT,
    hsn_code TEXT,
    description TEXT,
    gst_rate_details TEXT,
    gst_rate NUMERIC DEFAULT 0,
    type_of_supply TEXT DEFAULT 'Goods',
    rate_of_duty NUMERIC DEFAULT 0,
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Create Vouchers Table (Financial Transactions Header)
CREATE TABLE IF NOT EXISTS public.vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vno TEXT NOT NULL,
    date TEXT NOT NULL,
    type TEXT NOT NULL,
    particulars TEXT NOT NULL,
    account TEXT,
    party_id BIGINT REFERENCES public.parties(id) ON DELETE SET NULL,
    ledger_id BIGINT REFERENCES public.ledgers(id) ON DELETE SET NULL,
    item TEXT,
    qty NUMERIC,
    rate NUMERIC,
    advance NUMERIC,
    order_date TEXT,
    delivery_date TEXT,
    amount NUMERIC NOT NULL,
    dr BOOLEAN NOT NULL DEFAULT TRUE,
    narration TEXT,
    taxable_value NUMERIC DEFAULT 0,
    cgst NUMERIC DEFAULT 0,
    sgst NUMERIC DEFAULT 0,
    igst NUMERIC DEFAULT 0,
    total_with_tax NUMERIC DEFAULT 0,
    is_pending_update BOOLEAN DEFAULT FALSE,
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Create Voucher Line Items Table (Stock item lines per voucher)
CREATE TABLE IF NOT EXISTS public.voucher_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL REFERENCES public.vouchers(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    qty NUMERIC NOT NULL,
    rate NUMERIC NOT NULL,
    amount NUMERIC NOT NULL,
    gst_rate NUMERIC DEFAULT 0,
    hsn_code TEXT,
    taxable_value NUMERIC DEFAULT 0,
    cgst NUMERIC DEFAULT 0,
    sgst NUMERIC DEFAULT 0,
    igst NUMERIC DEFAULT 0
);

-- 8. Create Voucher Double-Entry Lines Table (Debit/Credit breakdown per voucher)
CREATE TABLE IF NOT EXISTS public.voucher_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL REFERENCES public.vouchers(id) ON DELETE CASCADE,
    ledger_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    dr BOOLEAN NOT NULL
);

-- 9. Create App Settings Table (Stores ALL app settings, Tally connection info, inventory rules, user configs)
CREATE TABLE IF NOT EXISTS public.app_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    user_id TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Create Audit Logs Table (Tracks all system changes & Tally XML payloads)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    action TEXT NOT NULL,
    details TEXT NOT NULL,
    xml_payload TEXT,
    tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id TEXT
);

-- MIGRATION HELPERS (Safely add user_id column if executing on pre-existing database)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='companies' AND column_name='user_id') THEN
        ALTER TABLE public.companies ADD COLUMN user_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='ledgers' AND column_name='user_id') THEN
        ALTER TABLE public.ledgers ADD COLUMN user_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='parties' AND column_name='user_id') THEN
        ALTER TABLE public.parties ADD COLUMN user_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='stock_items' AND column_name='user_id') THEN
        ALTER TABLE public.stock_items ADD COLUMN user_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vouchers' AND column_name='user_id') THEN
        ALTER TABLE public.vouchers ADD COLUMN user_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='app_settings' AND column_name='user_id') THEN
        ALTER TABLE public.app_settings ADD COLUMN user_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='audit_logs' AND column_name='user_id') THEN
        ALTER TABLE public.audit_logs ADD COLUMN user_id TEXT;
    END IF;
END $$;

-- =====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES & PERMISSIONS
-- Enables client access with Supabase anon/publishable key & authenticated users
-- =====================================================================

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledgers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Create Open & Auth Access Policies for all tables
DROP POLICY IF EXISTS "Allow public access for tenants" ON public.tenants;
CREATE POLICY "Allow public access for tenants" ON public.tenants FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for companies" ON public.companies;
CREATE POLICY "Allow public access for companies" ON public.companies FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for ledgers" ON public.ledgers;
CREATE POLICY "Allow public access for ledgers" ON public.ledgers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for parties" ON public.parties;
CREATE POLICY "Allow public access for parties" ON public.parties FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for stock_items" ON public.stock_items;
CREATE POLICY "Allow public access for stock_items" ON public.stock_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for vouchers" ON public.vouchers;
CREATE POLICY "Allow public access for vouchers" ON public.vouchers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for voucher_items" ON public.voucher_items;
CREATE POLICY "Allow public access for voucher_items" ON public.voucher_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for voucher_entries" ON public.voucher_entries;
CREATE POLICY "Allow public access for voucher_entries" ON public.voucher_entries FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for app_settings" ON public.app_settings;
CREATE POLICY "Allow public access for app_settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public access for audit_logs" ON public.audit_logs;
CREATE POLICY "Allow public access for audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime replication for instant UI updates
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.companies, public.ledgers, public.parties, public.stock_items, public.vouchers, public.app_settings;
  END IF;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- ─── Method 2 Admin Helper: Set/Update Authorized IP for User ───────────────
-- Run this function in Supabase SQL Editor to set or update allowed IP for any account.
-- Example: SELECT public.set_user_allowed_ip('user@domain.com', '203.0.113.19');
CREATE OR REPLACE FUNCTION public.set_user_allowed_ip(target_email text, target_ip text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id uuid;
BEGIN
  SELECT id INTO v_user_id FROM auth.users WHERE lower(email) = lower(target_email);
  IF v_user_id IS NULL THEN
    RETURN 'Error: User email "' || target_email || '" not found in Supabase Auth.';
  END IF;

  UPDATE auth.users
  SET raw_user_meta_data = jsonb_set(COALESCE(raw_user_meta_data, '{}'::jsonb), '{allowed_ip}', to_jsonb(target_ip))
  WHERE id = v_user_id;

  RETURN 'Success: Set allowed IP for ' || target_email || ' to ' || target_ip;
END;
$$;



